// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.linkedin.norbert.protos;

public final class NorbertProtos {
  private NorbertProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class NorbertMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use NorbertMessage.newBuilder() to construct.
    private NorbertMessage() {}
    
    private static final NorbertMessage defaultInstance = new NorbertMessage();
    public static NorbertMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public NorbertMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linkedin.norbert.protos.NorbertProtos.internal_static_norbert_NorbertMessage_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linkedin.norbert.protos.NorbertProtos.internal_static_norbert_NorbertMessage_fieldAccessorTable;
    }
    
    public static enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      OK(0, 0),
      ERROR(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Status valueOf(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return ERROR;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Status[] VALUES = {
        OK, ERROR, 
      };
      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.linkedin.norbert.protos.NorbertProtos.getDescriptor();
      }
    }
    
    // required sfixed64 request_id_msb = 1;
    public static final int REQUEST_ID_MSB_FIELD_NUMBER = 1;
    private boolean hasRequestIdMsb;
    private long requestIdMsb_ = 0L;
    public boolean hasRequestIdMsb() { return hasRequestIdMsb; }
    public long getRequestIdMsb() { return requestIdMsb_; }
    
    // required sfixed64 request_id_lsb = 2;
    public static final int REQUEST_ID_LSB_FIELD_NUMBER = 2;
    private boolean hasRequestIdLsb;
    private long requestIdLsb_ = 0L;
    public boolean hasRequestIdLsb() { return hasRequestIdLsb; }
    public long getRequestIdLsb() { return requestIdLsb_; }
    
    // optional .norbert.NorbertMessage.Status status = 10 [default = OK];
    public static final int STATUS_FIELD_NUMBER = 10;
    private boolean hasStatus;
    private com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status status_ = com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status.OK;
    public boolean hasStatus() { return hasStatus; }
    public com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status getStatus() { return status_; }
    
    // required string message_name = 11;
    public static final int MESSAGE_NAME_FIELD_NUMBER = 11;
    private boolean hasMessageName;
    private java.lang.String messageName_ = "";
    public boolean hasMessageName() { return hasMessageName; }
    public java.lang.String getMessageName() { return messageName_; }
    
    // optional bytes message = 12;
    public static final int MESSAGE_FIELD_NUMBER = 12;
    private boolean hasMessage;
    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessage() { return hasMessage; }
    public com.google.protobuf.ByteString getMessage() { return message_; }
    
    // optional string error_message = 13;
    public static final int ERROR_MESSAGE_FIELD_NUMBER = 13;
    private boolean hasErrorMessage;
    private java.lang.String errorMessage_ = "";
    public boolean hasErrorMessage() { return hasErrorMessage; }
    public java.lang.String getErrorMessage() { return errorMessage_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasRequestIdMsb) return false;
      if (!hasRequestIdLsb) return false;
      if (!hasMessageName) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasRequestIdMsb()) {
        output.writeSFixed64(1, getRequestIdMsb());
      }
      if (hasRequestIdLsb()) {
        output.writeSFixed64(2, getRequestIdLsb());
      }
      if (hasStatus()) {
        output.writeEnum(10, getStatus().getNumber());
      }
      if (hasMessageName()) {
        output.writeString(11, getMessageName());
      }
      if (hasMessage()) {
        output.writeBytes(12, getMessage());
      }
      if (hasErrorMessage()) {
        output.writeString(13, getErrorMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestIdMsb()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(1, getRequestIdMsb());
      }
      if (hasRequestIdLsb()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(2, getRequestIdLsb());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, getStatus().getNumber());
      }
      if (hasMessageName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getMessageName());
      }
      if (hasMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getMessage());
      }
      if (hasErrorMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getErrorMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.NorbertMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.linkedin.norbert.protos.NorbertProtos.NorbertMessage prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.newBuilder()
      private Builder() {}
      
      com.linkedin.norbert.protos.NorbertProtos.NorbertMessage result = new com.linkedin.norbert.protos.NorbertProtos.NorbertMessage();
      
      @Override
      protected com.linkedin.norbert.protos.NorbertProtos.NorbertMessage internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.linkedin.norbert.protos.NorbertProtos.NorbertMessage();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.getDescriptor();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.NorbertMessage getDefaultInstanceForType() {
        return com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.getDefaultInstance();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.NorbertMessage build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.linkedin.norbert.protos.NorbertProtos.NorbertMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.NorbertMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        com.linkedin.norbert.protos.NorbertProtos.NorbertMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linkedin.norbert.protos.NorbertProtos.NorbertMessage) {
          return mergeFrom((com.linkedin.norbert.protos.NorbertProtos.NorbertMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.linkedin.norbert.protos.NorbertProtos.NorbertMessage other) {
        if (other == com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.getDefaultInstance()) return this;
        if (other.hasRequestIdMsb()) {
          setRequestIdMsb(other.getRequestIdMsb());
        }
        if (other.hasRequestIdLsb()) {
          setRequestIdLsb(other.getRequestIdLsb());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMessageName()) {
          setMessageName(other.getMessageName());
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasErrorMessage()) {
          setErrorMessage(other.getErrorMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 9: {
              setRequestIdMsb(input.readSFixed64());
              break;
            }
            case 17: {
              setRequestIdLsb(input.readSFixed64());
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status value = com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                setStatus(value);
              }
              break;
            }
            case 90: {
              setMessageName(input.readString());
              break;
            }
            case 98: {
              setMessage(input.readBytes());
              break;
            }
            case 106: {
              setErrorMessage(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required sfixed64 request_id_msb = 1;
      public boolean hasRequestIdMsb() {
        return result.hasRequestIdMsb();
      }
      public long getRequestIdMsb() {
        return result.getRequestIdMsb();
      }
      public Builder setRequestIdMsb(long value) {
        result.hasRequestIdMsb = true;
        result.requestIdMsb_ = value;
        return this;
      }
      public Builder clearRequestIdMsb() {
        result.hasRequestIdMsb = false;
        result.requestIdMsb_ = 0L;
        return this;
      }
      
      // required sfixed64 request_id_lsb = 2;
      public boolean hasRequestIdLsb() {
        return result.hasRequestIdLsb();
      }
      public long getRequestIdLsb() {
        return result.getRequestIdLsb();
      }
      public Builder setRequestIdLsb(long value) {
        result.hasRequestIdLsb = true;
        result.requestIdLsb_ = value;
        return this;
      }
      public Builder clearRequestIdLsb() {
        result.hasRequestIdLsb = false;
        result.requestIdLsb_ = 0L;
        return this;
      }
      
      // optional .norbert.NorbertMessage.Status status = 10 [default = OK];
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Status.OK;
        return this;
      }
      
      // required string message_name = 11;
      public boolean hasMessageName() {
        return result.hasMessageName();
      }
      public java.lang.String getMessageName() {
        return result.getMessageName();
      }
      public Builder setMessageName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageName = true;
        result.messageName_ = value;
        return this;
      }
      public Builder clearMessageName() {
        result.hasMessageName = false;
        result.messageName_ = "";
        return this;
      }
      
      // optional bytes message = 12;
      public boolean hasMessage() {
        return result.hasMessage();
      }
      public com.google.protobuf.ByteString getMessage() {
        return result.getMessage();
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessage = true;
        result.message_ = value;
        return this;
      }
      public Builder clearMessage() {
        result.hasMessage = false;
        result.message_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }
      
      // optional string error_message = 13;
      public boolean hasErrorMessage() {
        return result.hasErrorMessage();
      }
      public java.lang.String getErrorMessage() {
        return result.getErrorMessage();
      }
      public Builder setErrorMessage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasErrorMessage = true;
        result.errorMessage_ = value;
        return this;
      }
      public Builder clearErrorMessage() {
        result.hasErrorMessage = false;
        result.errorMessage_ = "";
        return this;
      }
    }
    
    static {
      com.linkedin.norbert.protos.NorbertProtos.getDescriptor();
    }
  }
  
  public static final class Node extends
      com.google.protobuf.GeneratedMessage {
    // Use Node.newBuilder() to construct.
    private Node() {}
    
    private static final Node defaultInstance = new Node();
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linkedin.norbert.protos.NorbertProtos.internal_static_norbert_Node_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linkedin.norbert.protos.NorbertProtos.internal_static_norbert_Node_fieldAccessorTable;
    }
    
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // required string url = 2;
    public static final int URL_FIELD_NUMBER = 2;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // repeated int32 partition = 3;
    public static final int PARTITION_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> partition_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getPartitionList() {
      return partition_;
    }
    public int getPartitionCount() { return partition_.size(); }
    public int getPartition(int index) {
      return partition_.get(index);
    }
    
    @Override
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasUrl) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasUrl()) {
        output.writeString(2, getUrl());
      }
      for (int element : getPartitionList()) {
        output.writeInt32(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getUrl());
      }
      {
        int dataSize = 0;
        for (int element : getPartitionList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getPartitionList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.linkedin.norbert.protos.NorbertProtos.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.linkedin.norbert.protos.NorbertProtos.Node prototype) {
      return new Builder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.linkedin.norbert.protos.NorbertProtos.Node.newBuilder()
      private Builder() {}
      
      com.linkedin.norbert.protos.NorbertProtos.Node result = new com.linkedin.norbert.protos.NorbertProtos.Node();
      
      @Override
      protected com.linkedin.norbert.protos.NorbertProtos.Node internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.linkedin.norbert.protos.NorbertProtos.Node();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linkedin.norbert.protos.NorbertProtos.Node.getDescriptor();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.Node getDefaultInstanceForType() {
        return com.linkedin.norbert.protos.NorbertProtos.Node.getDefaultInstance();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.Node build() {
        if (result != null && !isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.linkedin.norbert.protos.NorbertProtos.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.linkedin.norbert.protos.NorbertProtos.Node buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");  }
        if (result.partition_ != java.util.Collections.EMPTY_LIST) {
          result.partition_ =
            java.util.Collections.unmodifiableList(result.partition_);
        }
        com.linkedin.norbert.protos.NorbertProtos.Node returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linkedin.norbert.protos.NorbertProtos.Node) {
          return mergeFrom((com.linkedin.norbert.protos.NorbertProtos.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.linkedin.norbert.protos.NorbertProtos.Node other) {
        if (other == com.linkedin.norbert.protos.NorbertProtos.Node.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (!other.partition_.isEmpty()) {
          if (result.partition_.isEmpty()) {
            result.partition_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.partition_.addAll(other.partition_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setUrl(input.readString());
              break;
            }
            case 24: {
              addPartition(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // required string url = 2;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
      
      // repeated int32 partition = 3;
      public java.util.List<java.lang.Integer> getPartitionList() {
        return java.util.Collections.unmodifiableList(result.partition_);
      }
      public int getPartitionCount() {
        return result.getPartitionCount();
      }
      public int getPartition(int index) {
        return result.getPartition(index);
      }
      public Builder setPartition(int index, int value) {
        result.partition_.set(index, value);
        return this;
      }
      public Builder addPartition(int value) {
        if (result.partition_.isEmpty()) {
          result.partition_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.partition_.add(value);
        return this;
      }
      public Builder addAllPartition(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.partition_.isEmpty()) {
          result.partition_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.partition_);
        return this;
      }
      public Builder clearPartition() {
        result.partition_ = java.util.Collections.emptyList();
        return this;
      }
    }
    
    static {
      com.linkedin.norbert.protos.NorbertProtos.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_norbert_NorbertMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_norbert_NorbertMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_norbert_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_norbert_Node_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\rnorbert.proto\022\007norbert\"\317\001\n\016NorbertMess" +
      "age\022\026\n\016request_id_msb\030\001 \002(\020\022\026\n\016request_i" +
      "d_lsb\030\002 \002(\020\0222\n\006status\030\n \001(\0162\036.norbert.No" +
      "rbertMessage.Status:\002OK\022\024\n\014message_name\030" +
      "\013 \002(\t\022\017\n\007message\030\014 \001(\014\022\025\n\rerror_message\030" +
      "\r \001(\t\"\033\n\006Status\022\006\n\002OK\020\000\022\t\n\005ERROR\020\001\"2\n\004No" +
      "de\022\n\n\002id\030\001 \002(\005\022\013\n\003url\030\002 \002(\t\022\021\n\tpartition" +
      "\030\003 \003(\005B.\n\033com.linkedin.norbert.protosB\rN" +
      "orbertProtosH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_norbert_NorbertMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_norbert_NorbertMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_norbert_NorbertMessage_descriptor,
              new java.lang.String[] { "RequestIdMsb", "RequestIdLsb", "Status", "MessageName", "Message", "ErrorMessage", },
              com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.class,
              com.linkedin.norbert.protos.NorbertProtos.NorbertMessage.Builder.class);
          internal_static_norbert_Node_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_norbert_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_norbert_Node_descriptor,
              new java.lang.String[] { "Id", "Url", "Partition", },
              com.linkedin.norbert.protos.NorbertProtos.Node.class,
              com.linkedin.norbert.protos.NorbertProtos.Node.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
